version: '3.8'

services:
  calendar-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Add volumes if you need to persist data
    # volumes:
    #   - ./data:/app/data 